version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/mosaku

hooks:
  BeforeInstall:
    - location: scripts/clear_cache.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
    - location: scripts/install_composer_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_php_fpm.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/check_service.sh
      timeout: 300
      runas: root
